### ISSUE TITLE
Do I still need Overthrow in 2015?

### ISSUE THREAD

**Issue by dt1973** [filamentgroup/Overthrow#89]
Hi!

Is Overthrow still needed in 2015 for mobile web / PhoneGap? Doesn't the majority of mobile users now use modern touch devices that support overflow scrolling? And won't using a polyfill on older devices for something as complicated as scrolling just create more problems than it solves?

Thanks!

**Comment by toddparker** [comment]
We still use overthrow because it gives us peace of mind that we won't break anyone's experience if overflow isn't supported. This is a feature test (with some wonky browsers thrown out) that then applies standard CSS scrolling, it's not a polyfill like iScroll. Since it's light and uses native capabilities it seems worth including for a while longer if you want to support the broadest possible audience but YMMV.

**Comment by scottjehl** [comment]
Thanks Todd. I think it would be a nice idea to revisit our current logic and checks and see if anything can be updated here for sure.
