### ISSUE TITLE
0.7.1 should be 0.8, if not 1.x

### ISSUE THREAD

**Issue by shlomiassaf** [filamentgroup/Overthrow#91]
Changing the module name causes broken references in builds using commnJS.

This is an API breaking change.

**Comment by scottjehl** [comment]
hmm. Okay, I'd agree but this plugin does not yet export to commonjs (that's on the horizon but I haven't done it yet). It wasn't published to npm yet either. This change made for the first npm push, since there's another package published under the overthrow name on npm.

Make sense or am I missing the point? Thanks

**Comment by shlomiassaf** [comment]
You're right but with smart bundlers, such as Webpack, its easy to overcome packages without commonJS support.

This was my previous "require":
'require('imports?this=>window!overthrow/src/overthrow-detect.js');'

After you change today, all my CI builds failed, had to change to:
'require('imports?this=>window!fg-overthrow/src/overthrow-detect.js');'

Every webpack project, using your package as npm module via github link will fail now.

BTW, once you support commonJS, its also a breaking api change, I will have to remove the loader that sets "this" to window.

**Comment by scottjehl** [comment]
That’s good feedback, thanks. And helpful to see your web pack setup. 

I’ll change the version to 0.8 and deprecate this one. Sound good?

**Comment by shlomiassaf** [comment]
Yep, little bit more work but its the right way
